version: '3'

networks:
  internal:
    external: false

services:
  db:
    image: postgres:9.6.6-alpine
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: BAKER
      POSTGRES_PASSWORD: TRYBAKERPASSWORD
  loyalty-api:
    build: ./api
    ports:
      - "3000:3000"
    depends_on:
      - "db"
  loyalty-frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    depends_on:
      - "loyalty-api"


