version: '3'

networks:
  internal:
    external: false

services:
  loyalty-api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - "postgres"
    networks:
      - "internal"
  postgres:
    image: postgres:9.6.6-alpine
    ports:
      - "5432:5432"
    networks:
      - "internal"
    environment:
      POSTGRES_PASSWORD: TRYBAKERPASSWORD
